//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp18 {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp18.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Deniz Ürünleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tatlılar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button3 {
            get {
                return ResourceManager.GetString("button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkımızda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button5 {
            get {
                return ResourceManager.GetString("button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label102 {
            get {
                return ResourceManager.GetString("label102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label105 {
            get {
                return ResourceManager.GetString("label105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label107 {
            get {
                return ResourceManager.GetString("label107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label110 {
            get {
                return ResourceManager.GetString("label110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label112 {
            get {
                return ResourceManager.GetString("label112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label113 {
            get {
                return ResourceManager.GetString("label113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label116 {
            get {
                return ResourceManager.GetString("label116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label117 {
            get {
                return ResourceManager.GetString("label117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label121 {
            get {
                return ResourceManager.GetString("label121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label122 {
            get {
                return ResourceManager.GetString("label122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label123 {
            get {
                return ResourceManager.GetString("label123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label126 {
            get {
                return ResourceManager.GetString("label126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label128 {
            get {
                return ResourceManager.GetString("label128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label131 {
            get {
                return ResourceManager.GetString("label131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label133 {
            get {
                return ResourceManager.GetString("label133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label136 {
            get {
                return ResourceManager.GetString("label136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label145 {
            get {
                return ResourceManager.GetString("label145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label146 {
            get {
                return ResourceManager.GetString("label146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label147 {
            get {
                return ResourceManager.GetString("label147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label148 {
            get {
                return ResourceManager.GetString("label148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label159 {
            get {
                return ResourceManager.GetString("label159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label161 {
            get {
                return ResourceManager.GetString("label161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label175 {
            get {
                return ResourceManager.GetString("label175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label177 {
            get {
                return ResourceManager.GetString("label177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label181 {
            get {
                return ResourceManager.GetString("label181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label184 {
            get {
                return ResourceManager.GetString("label184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label186 {
            get {
                return ResourceManager.GetString("label186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label190 {
            get {
                return ResourceManager.GetString("label190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label193 {
            get {
                return ResourceManager.GetString("label193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label195 {
            get {
                return ResourceManager.GetString("label195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label196 {
            get {
                return ResourceManager.GetString("label196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label197 {
            get {
                return ResourceManager.GetString("label197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label201 {
            get {
                return ResourceManager.GetString("label201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label204 {
            get {
                return ResourceManager.GetString("label204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   protin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label206 {
            get {
                return ResourceManager.GetString("label206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label207 {
            get {
                return ResourceManager.GetString("label207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YAPILIŞ TARİHİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label31 {
            get {
                return ResourceManager.GetString("label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   şekeroranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label32 {
            get {
                return ResourceManager.GetString("label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YAPILIŞ TARİHİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label34 {
            get {
                return ResourceManager.GetString("label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   şekeroranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label35 {
            get {
                return ResourceManager.GetString("label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sadece benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label41 {
            get {
                return ResourceManager.GetString("label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label44 {
            get {
                return ResourceManager.GetString("label44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label49 {
            get {
                return ResourceManager.GetString("label49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label53 {
            get {
                return ResourceManager.GetString("label53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sepete Git benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label61 {
            get {
                return ResourceManager.GetString("label61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   makaron benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label64 {
            get {
                return ResourceManager.GetString("label64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daği tatlısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label69 {
            get {
                return ResourceManager.GetString("label69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antepli Makaron benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label72 {
            get {
                return ResourceManager.GetString("label72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yapılış tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label73 {
            get {
                return ResourceManager.GetString("label73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   şekeroranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label76 {
            get {
                return ResourceManager.GetString("label76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vitaminA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label78 {
            get {
                return ResourceManager.GetString("label78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alarji yapabilecekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label79 {
            get {
                return ResourceManager.GetString("label79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alarji yapabilecekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label80 {
            get {
                return ResourceManager.GetString("label80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alarji yapabilecekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label87 {
            get {
                return ResourceManager.GetString("label87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label91 {
            get {
                return ResourceManager.GetString("label91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yağ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label97 {
            get {
                return ResourceManager.GetString("label97", resourceCulture);
            }
        }
    }
}
